name: moneylog
description: "A comprehensive personal finance management app that helps you track and analyze your expenses, income, and financial transactions."

# Prevents accidental publishing to pub.dev
publish_to: 'none'  # Remove this line to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter
  sms_advanced: ^1.1.0
  permission_handler: any
  table_calendar: ^3.0.9
  file_picker: ^10.2.0
  flutter_launcher_icons: ^0.12.0

  # Cupertino Icons for iOS style icons
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.5
  intl: ^0.20.2
  flutter_date_pickers: ^0.4.3
  fl_chart: ^1.0.0
  provider: ^6.1.5
  local_auth: ^2.1.7
  flutter_local_notifications: ^19.3.0
  shared_preferences: ^2.5.3
  dynamic_color: ^1.7.0
  flutter_colorpicker: ^1.0.3
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting and code quality
  flutter_lints: ^6.0.0

flutter_icons:
  android: true
  image_path: "assets/icon/app_icon.png"
  
flutter:
  uses-material-design: true
  
  # Assets configuration
  assets:
    - assets/icon/
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
